version: '3.8'

services:
  pldraw-dash:
    build: 
      context: .
      tags:
        - pldraw-dash:latest
    ports:
      - "8050:8050"
    volumes:
      - ./image:/app/image
    restart: unless-stopped
