version: '3.8'

services:
  pldraw-dash:
    container_name: pldraw-dash
    image: pldraw-dash:latest
    build: 
      context: .
    ports:
      - "8050:8050"
    volumes:
      - ./image:/app/image
    restart: unless-stopped
